# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 00:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dangers_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_To_Danger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 2, 8, 0, 54, 57, 151398, tzinfo=utc))),
                ('photo', models.ImageField(upload_to='imagenes/comments')),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='dangers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 0, 54, 57, 148626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dangers',
            name='photo',
            field=models.ImageField(upload_to='imagenes/dangers'),
        ),
        migrations.AddField(
            model_name='comment_to_danger',
            name='danger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dangers'),
        ),
    ]
