# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190208_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangers',
            name='state',
            field=models.CharField(choices=[('sin_control', 'sin_control'), ('controlado', 'controlado'), ('eliminado', 'eliminado')], max_length=2000),
        ),
    ]
