# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190208_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangers',
            name='floor_number',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
    ]
