# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dangers_floor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangers',
            name='id_management_system',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
