# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dangers_id_management_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Of_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
    ]
