# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dangers_area_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions_From_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=2000)),
                ('photo', models.ImageField(blank=True, upload_to='imagenes/suggestions')),
            ],
        ),
    ]
